task_tracker/urls.py
from django.urls import path
from . import views
app_name = 'task_tracker'
urlpatterns = [
    path('task/list', views.TaskListView.as_view(),
         name="task_list"),
    path('task/create', views.TaskFormView.as_view(), name="task_create"),
    path('task/<int:pk>/update', views.TaskFormView.as_view(),
         name="task_update"),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_tracker.urls',
                     namespace='task_tracker')),
    path('login/', auth_views.LoginView.as_view(
        redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('api/auth/', include('authentication.api.urls',
                              namespace='authentication')),
]

task_tracker/models.py
from django.db import models
from django.conf import settings

STATUS_CHOICES = (
    (0, "Планируется"),
    (1, "Активная"),
    (2, "Контроль"),
    (3, "Завершена")
)


# Базовый абстрактный класс
class ItemBase(models.Model):
    title = models.CharField(max_length=180)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


# Задача
class Task(ItemBase):
    description = models.TextField()
    performer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='performer_tasks')
    observers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name='observers_tasks')
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField(null=True, blank=True)
    planned_end_datetime = models.DateTimeField()


# Чек лист задачи
class TaskChekList(ItemBase):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)


# Изменение статуса
class StatusChange(models.Model):
    previous_status = models.IntegerField(choices=STATUS_CHOICES)
    next_status = models.IntegerField(choices=STATUS_CHOICES)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


# Напоминание
class Reminder(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    description = models.TextField()
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)

task_tracker/forms.py
from datetime import datetime, date
from django import forms
from .models import Task


# Форма задачи
class TaskForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(
        format=('%Y-%m-%d')))
    start_time = forms.TimeField()
    end_date = forms.DateField(widget=forms.DateInput(
        format=('%Y-%m-%d')), required=False)
    end_time = forms.TimeField(required=False)
    planned_end_date = forms.DateField(
        widget=forms.DateInput(format=('%Y-%m-%d')))
    planned_end_time = forms.TimeField()

    class Meta:
        model = Task
        fields = [
            'title', 'description', 'performer',
            'observers', 'start_date', 'start_time',
            'end_date', 'end_time', 'status',
            'planned_end_date', 'planned_end_time',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if kwargs['instance']:
            self.fields['start_date'].initial = \
                kwargs['instance'].start_datetime.date()
            self.fields['start_time'].initial = \
                kwargs['instance'].start_datetime.time()
            if self.fields['end_date'].initial and self.fields['end_time'].initial:
                self.fields['end_date'].initial = \
                    kwargs['instance'].end_datetime.date()
                self.fields['end_time'].initial = \
                    kwargs['instance'].end_datetime.time()
            self.fields['planned_end_date'].initial = \
                kwargs['instance'].planned_end_datetime.date()
            self.fields['planned_end_time'].initial = \
                kwargs['instance'].planned_end_datetime.time()
        else:
            self.fields['start_date'].initial = date.today()
            self.fields['start_time'].initial = datetime.now().time()

    def save(self, commit=True):
        end_datetime = None
        start_datetime = datetime.combine(self.cleaned_data['start_date'],
                                          self.cleaned_data['start_time'])
        if self.cleaned_data['end_date'] and self.cleaned_data['end_time']:
            end_datetime = datetime.combine(self.cleaned_data['end_date'],
                                            self.cleaned_data['end_time'])
        planned_end_datetime = datetime.combine(
            self.cleaned_data['planned_end_date'],
            self.cleaned_data['planned_end_time'])
        form = super(TaskForm, self).save(commit=False)
        form.start_datetime = start_datetime
        form.end_datetime = end_datetime
        form.planned_end_datetime = planned_end_datetime
        if commit:
            form.save()
            self.save_m2m()
        return form

task_tracker/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.list import ListView
from django.forms.models import inlineformset_factory
from django.views.generic.base import TemplateResponseMixin, View
from .models import Task, TaskChekList
from .forms import TaskForm


# Список задач
class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'task_tracker/task/list.html'
    model = Task
    context_object_name = 'tasks'


# Обновление и создания задачи
class TaskFormView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'task_tracker/task/form.html'
    task = None

    def get_task_checklist_formset(self, data=None):
        TaskFormSet = inlineformset_factory(
            Task,
            TaskChekList,
            fields=['title', 'is_completed'],
            extra=0, can_delete=True)
        return TaskFormSet(
            instance=self.task, data=data)

    def dispatch(self, *args, **kwargs):
        self.task = self.kwargs.get('pk', None)
        if self.task:
            self.task = get_object_or_404(Task, id=self.task)
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        task_form = TaskForm(instance=self.task)
        task_checklist_formset = self.get_task_checklist_formset()
        return self.render_to_response({
            'task_form': task_form,
            'task_checklist_formset': task_checklist_formset})

    def post(self, request, *args, **kwargs):
        task_form = TaskForm(data=request.POST, instance=self.task)
        task_checklist_formset = self.get_task_checklist_formset(
            data=request.POST)
        if task_form.is_valid() and task_checklist_formset.is_valid():
            task = task_form.save()
            task_checklists = task_checklist_formset.save(
                commit=False
            )
            for task_checklist in task_checklists:
                task_checklist.task = task
                task_checklist.save()
        task_deleted_objects = task_checklist_formset.deleted_objects
        for task_deleted in task_deleted_objects:
            task_deleted.delete()
        return redirect('task_tracker:task_list')

templates/task_tracker/task/form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<form method="POST" action="">
	{% csrf_token %}
	<h3 style="display: inline;">Добавить новую задачу </h3><br><br>
	<div class="form-group">
	    <label for="email">название:</label><br>
	    {{ task_form.title }}
	</div>
	<div class="form-group">
	    <label for="email">Описание:</label><br>
	    {{ task_form.description }}
	</div>
	<div class="form-group">
	    <label for="email">исполнитель:</label><br>
	    {{ task_form.performer }}
	</div>
	<div class="form-group">
	    <label for="email">наблюдатели:</label><br>
	    {{ task_form.observers }}
	</div>
	<div class="form-group">
	    <label for="email">статус:</label><br>
	    {{ task_form.status }}
	</div>
	<div class="form-group">
	    <label for="email">Дата и время начала:</label> <br>
	    {{ task_form.start_date|attr:"type:date" }}
		{{ task_form.start_time|attr:"type:time" }}
	</div>
	<div class="form-group">
	    <label for="email">Дата и время завершения:</label> <br>
	    {{ task_form.end_date|attr:"type:date" }}
		{{ task_form.end_time|attr:"type:time" }}
	</div>
	<div class="form-group">
	    <label for="email">планируемое дата и время завершения:</label> <br>
	    {{ task_form.planned_end_date|attr:"type:date" }}
	{{ task_form.planned_end_time|attr:"type:time" }}
	</div><br>
	<div class="form-group formset">
		{{ task_checklist_formset.management_form }}
	    <label for="email">Чек лист: </label> <button class="btn-sm btn-primary add-inline-form">+</button><br>
	    <div class="formset-forms">
            {% for task_checklist in task_checklist_formset %}
              <div class="form-group formset-form">
                {% for hidden in task_checklist.hidden_fields %}
                  {{ hidden }}
                {% endfor %}
                {{ task_checklist.title }}
                {{ task_checklist.is_completed }}
                {{ task_checklist.DELETE }}
              </div>
            {% endfor %}
          </div>
          <div class="form-group empty-form d-none">
              {{ task_checklist_formset.empty_form.title }}
              {{ task_checklist_formset.empty_form.is_completed }}
              {{ task_checklist_formset.empty_form.DELETE }}
            </div>
          </div>
	</div><br>
	<input type="submit" class="btn btn-success" name="" value="Сохранить"><br><br>
</form>
{% endblock %}

templates/task_tracker/task/list.html
{% extends "base.html" %}
{% load task_tracker_tags %}
{% block content %}
  <h3 style="display: inline;">Список задач </h3>
  <a href="{% url 'task_tracker:task_create' %}" class="btn btn-success pull-right" style="float: right;">+ Добавить новую задачу</a><br><br>
  
  <table class="table table-bordered">
    <tr>
      <th>Название</th>
      <th>Описание</th>
      <th>Исполнитель</th>
      <th>Наблюдатели</th>
      <th>Статус</th>
      <th>Время начала</th>
      <th>Время завершения</th>
      <th>Планируемое время завершения</th>
      <th>Чек лист</th>
    </tr>
    {% for task in tasks %}
      <tr>
        <td>{{ task.title }}</td>
        <td>{{ task.description }}</td>
        <td>{{ task.performer.get_full_name }}</td>
        <td>
          {% for observer in task.observers.all %}
            {{ observer.get_full_name }} <br>
          {% endfor %}
        </td>
        <td>{{ task.get_status_display }}</td> 
        <td>{{ task.start_datetime|date:'d.m.Y H:i' }}</td>
        <td>{{ task.end_datetime|date:'d.m.Y H:i' }}</td>
        <td>{{ task.planned_end_datetime|date:'d.m.Y H:i' }}</td>
        <td>
          {% for taskcheklist in task.taskcheklist_set.all %}
            {{ taskcheklist.title }}
            {% if taskcheklist.is_completed %}
              [Выполнен]
            {% else %}
              [Не выполнен]
            {% endif %}
          {% empty %}
            ----
          {% endfor %}
        </td>
        <td>
          {% is_expired task.end_datetime as is_expired %}
          {% if is_expired %}
              <span style="color: red;">Просрочена</span>
          {% endif %}
          <a href="{% url 'task_tracker:task_update' pk=task.id %}">Обновить</a>
        </td>

      </tr>
    {% endfor %}
  </table>
{% endblock %}